[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Route API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:; connect-src 'self' https: http://localhost:*; img-src 'self' data: blob: https:; media-src 'self' data: blob: https:;"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
